### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by NelsonRock** [lmc-eu/ngx-library#47]
Sorry for my english, I'am French guy!

Hello! great  awsome library!!

Firts at all, i would like to write something like this before die jejej!!

Second: How can i configure this library inside a project tha already exist?

For example: 
-what script must to be include? stupid question!!! {loader.js, ngx.js (of course), config.js, loader.js

Thanks for your answer!!

**Comment by OndraM** [comment]
Sorry, but the project is no longer maintained.
